#+TITLE: Артикли
#+OPTIONS: H:2 num:nil toc:nil html-postamble:nil

[[../english.html][Main]]

* Исчисляемые сущ. это ожидаемо те, которые можно посчитать - они имеют мн. и ед. форму:
one book, two books, three books\\
*Английские аборигены добавляют "a/an" перед исчисляемыми сущ. в ед. ч.*\\
a - перед согласными *звуками*\\
an - перед гласными *звуками*\\
a hat, an umbrella, *an* hours
* Неисчисляемые сущ. посчитать нельзя и они обычно мн. формы обычно не имеют:
*еда*: cheese, butter(масло), meat, salt, pepper(перец), bacon(бекон), bread, chocolate, honey(мед), jam\\
*жидкости*: coffe, milk, water, tea, wine, lemonade, petrol(бензин), oil\\
*материалы*: gold, iron(железо), silver(серебро), wood, paper\\
*абстрактные сущ.*: beauty(красота), love, happiness\\
*и другие*: hair(волосы), money, news, show, furniture(мебель), weather, advice(совет)
* Неисчисляемые сущ. следуют за глаголами в ед. числе, не используется *a / an* или *one*, но возможно использование *some*, которое так же используется с исчисляемыми сущ. во мн. ч.
Итого:\\
*some + неисчисляемые сущ.*\\
*some + исчисляемые сущ. во мн. ч.*\\
Примеры:\\
There is *some* meat in the fridge (но не: There are +some meats+ in the fridge)\\
There is *some* bread on the table (но не: There is +a bread+ on the table)
* Возможно использование исчисляемых и неисчисляемых сущ.  после фраз количества + *of*.
таких как:\\
|--------+---------------------|
| jar    | банка               |
| bottle |                     |
| piece  |                     |
| loaf   | булка               |
| cup    |                     |
| bar    | кусок               |
| glass  | стакан              |
| kilo   |                     |
| carton | коробка (картонная) |
| bowl   | миска, чаша         |
| can    | коробка (жестяная)  |
| jug    | кувшин              |
| slice  | ломоть              |
| tin    | консервная банка    |
| packet | пакет, пачка        |
н-р:\\
Do not forget to buy me *a jar of olives*\\
They opened *ten bottles of champagne* (вот так они извратили "шампанское")
* Притяжательная форма
В предложениях типа The girl's apple артикль the относится к обладателю, а не к обладаемому предмету. Каждое существительное может иметь только один определитель. В данном примере яблоко определяет принадлежность девочке, а вот определённая или нет девочка задаётся артиклем впереди, в данном случае - определённая, перевод - этой девочки яблоко, или более естественный вариант - яблоко этой девочки.
